= Submoduler
:url: https://github.com/rubyists/submoduler
:coc: {url}/blob/main/CODE_OF_CONDUCT.md[Code of Conduct]
:repo: {url}[submoduler repo]
:mit: https://opensource.org/licenses/MIT[MIT License]
:gems_url: https://rubygems.org
:rubygems: {gems_url}[rubygems.org]
:gempage: {gems_url}/gems/submoduler[Submoduler gem]

Simple tool for manipulating git submodules

== Installation

Install the gem and add to the application's Gemfile by executing:

    $ bundle add submoduler

If bundler is not being used to manage dependencies, install the gem by executing:

    $ gem install submoduler

== Usage

Coming soon

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake test` to run the tests.
You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`.
To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`.
This will create a git tag for the version, push git commits and the created tag, and push the `.gem` file to {rubygems}.

== Contributing

Bug reports, feature requests, and pull requests are welcome on GitHub at the {repo}.

== License

The gem is available as open source under the terms of the {mit}.

== Code of Conduct

Everyone interacting in the Submoduler project's codebases, issue trackers, chat rooms and mailing lists is expected to follow the {coc}.
